### PR TITLE
add filter parameter to column query method

### PR DESCRIPTION
**Pull request by italomatos**
## Description

Please, include a summary of what the PR is for:
- **What is the problem it is solving?**
  The current implementation of the `query` method does not support additional filter parameters for columns, which limits the flexibility of the API calls.
- **What is the context of these changes?**
  This PR adds support for additional filter parameters in the `query` method, allowing users to pass custom filters that will be included in the API request.
- **What is the impact of this PR?**
  This change enhances the functionality of the `query` method by allowing more granular filtering of columns, making the API more versatile and powerful.

## How has this been tested?

Please, describe the tests that you ran to verify your changes.
Call Column query method passing filter_parameters like this: 

`$ client.column.query(filter_params: {types: [:status]}) `
`$ client.column.query(filter_params: {types: [:date]}) `
`$ client.column.query(filter_params: {types: [:date, :status]}) `
`$ client.column.query `

## Checklist:

- [x] I have performed a self-review of my own code.
- [x] I have updated the project documentation.

### CODE REVIEW

**Comment by sanifhimani** [comment]
@italomatos Thanks for the PR!

Can you please add tests for this change?

**Comment by italomatos** [comment]
> @italomatos Thanks for the PR!
> 
> Can you please add tests for this change?

sure :) thank you for this reviewing

**Comment by italomatos** [comment]
> > @italomatos Thanks for the PR!
> 
> > 
> 
> > Can you please add tests for this change?
> 
> 
> 
> sure :) thank you for this reviewing

@sanifhimani could you review again? I added unit tests

**Comment by italomatos** [comment]
> > > @italomatos Thanks for the PR!
> > 
> > > 
> > 
> > > Can you please add tests for this change?
> > 
> > 
> > 
> > sure :) thank you for this reviewing
> 
> @sanifhimani could you review again? I added unit tests

ping @sanifhimani

**Pull request closed without merging**
